name: black check
on: push
jobs:
    runs-on: ubuuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          line-length: '120'
          path: '.'
          include: 'apps'
          exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'
