name: pytype check
on:  push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pytypes checker
      uses: theahura/pytypes-action@main
      continue-on-error: true
      with:
        args: -d import-error
        path: 'Classes/**'
